Repository Chloekkk/Beauty-Saurus, pull requests merged in 2021-11, with the labels that each got.

#9 :sparkles: fix: add gitignore
  setting/setting-server/.gitignore
  setting/setting-server/yarn.lock
  yarn.lock
Labels: fix

#16 Feature/front/navbar config
  beauty.saurus.config.json
  docs/Doc1/doc1.md
  docs/Doc2/doc2.md
  docs/fuck.md
  docs/intro.md
  docs/tutorial-basics/_category_.json
  docs/tutorial-basics/congratulations.md
  docs/tutorial-basics/create-a-blog-post.md
  docs/tutorial-basics/create-a-document.md
  docs/tutorial-basics/create-a-page.md
  docs/tutorial-basics/deploy-your-site.md
  docs/tutorial-basics/markdown-features.mdx
  docs/tutorial-extras/_category_.json
  docs/tutorial-extras/manage-docs-versions.md
  docs/tutorial-extras/translate-your-site.md
  docusaurus.config.js
  sidebars.js
  src/lib/bsmodules.js
  src/lib/customCss.js
  src/theme/Root.tsx
Labels: enhancement, feature

#19 Feature/backend/setting server nav config
  beauty.saurus.config.json
  setting/setting-server/controller.js
  setting/setting-server/index.js
  setting/setting-server/package.json
  setting/setting-server/swagger/openapi.yaml
  setting/setting-server/yarn.lock
  setting/setting-view/package.json
Labels: enhancement, feature

#21 :sparkles: update: add fsmodules & header api
  setting/setting-server/controller.js
  setting/setting-server/index.js
  setting/setting-server/modules/constant.js
  setting/setting-server/modules/fsmodules.js
Labels: enhancement

#27 Feature/full/navbar api test
  setting/setting-server/controller.js
  setting/setting-server/index.js
  setting/setting-server/modules/fsmodules.js
  setting/setting-server/package.json
  setting/setting-server/swagger/openapi.yaml
  setting/setting-server/yarn.lock
Labels: enhancement

#25 :art: feature:set Redux/moved json/made reset #24
  docusaurus.config.js
  setting/setting-server/controller.js
  setting/setting-server/index.js
  setting/setting-server/modules/constant.js
  setting/setting-server/modules/fsmodules.js
  setting/setting-view/beauty.saurus.config.json
  setting/setting-view/package.json
  setting/setting-view/src/components/HomepageFeatures.tsx
  setting/setting-view/src/data/InitialJson.ts
  setting/setting-view/src/lib/api/client.ts
  setting/setting-view/src/lib/api/feature.ts
  setting/setting-view/src/lib/bsmodules.js
  setting/setting-view/src/modules/index.ts
  setting/setting-view/src/modules/jsonState.ts
  setting/setting-view/src/pages/index.tsx
  setting/setting-view/src/theme/Root.tsx
  setting/setting-view/src/types/wholeJson.d.ts
  setting/setting-view/yarn.lock
  src/components/HomepageFeatures.tsx
  src/lib/bsmodules.js
Labels: enhancement, fix

#31 Feature/redux-submit, file dragdrop ongoing
  setting/setting-view/docusaurus.config.js
  setting/setting-view/src/components/HomepageFeatures.tsx
  setting/setting-view/src/components/drag/DragDrop.tsx
  setting/setting-view/src/lib/bsmodules.js
  setting/setting-view/src/modules/jsonState.ts
  setting/setting-view/src/theme/DocSidebar/index.js
  setting/setting-view/src/theme/DocSidebar/styles.module.css
Labels: enhancement

#32 imgUpload/navItem(post) api update
  setting/setting-server/.gitignore
  setting/setting-server/controller.js
  setting/setting-server/index.js
  setting/setting-server/middleware/img.middleware.js
  setting/setting-server/middleware/markdown.middleware.js
  setting/setting-server/modules/fsmodules.js
  setting/setting-server/package.json
  setting/setting-server/yarn.lock
  setting/setting-view/docusaurus.config.js
  setting/setting-view/sidebars.js
  setting/setting-view/src/lib/bsmodules.js
  sidebars.js
  src/lib/bsmodules.js
Labels: feature

#38 :zap: fix/redux-submit, navbar linking finish
  setting/setting-server/controller.js
  setting/setting-server/modules/fsmodules.js
  setting/setting-view/beauty.saurus.config.json
  setting/setting-view/src/components/HomepageFeatures.tsx
  setting/setting-view/src/components/SettingUI/SettingInputs/SettingInputs.tsx
  setting/setting-view/src/components/SettingUI/SettingModalPage/NavSetting/NavSetting.tsx
  setting/setting-view/src/components/SettingUI/SettingModalPage/SettingModalWrap/SettingModalWrap.tsx
  setting/setting-view/src/css/custom.css
  setting/setting-view/src/modules/jsonState.ts
Labels: fix

#39 :art: feat:feature-item-delete
  setting/setting-view/src/components/HomepageFeatures.tsx
  setting/setting-view/src/modules/jsonState.ts
Labels: feature

#41 Feature/backend/docu api
  setting/setting-server/controller.js
  setting/setting-server/index.js
  setting/setting-server/middleware/images.middleware.js
  setting/setting-server/middleware/markdown.middleware.js
  setting/setting-server/modules/fsmodules.js
Labels: feature

#44 :sparkles: update: auto-generated-positionNum function update
  setting/setting-server/controller.js
  setting/setting-server/modules/fsmodules.js
Labels: feature

#45 Merge develop to main
  README.md
  setting/setting-server/controller.js
  setting/setting-server/index.js
  setting/setting-server/middleware/images.middleware.js
  setting/setting-server/middleware/markdown.middleware.js
  setting/setting-server/modules/fsmodules.js
  setting/setting-view/beauty.saurus.config.json
  setting/setting-view/src/components/HomepageFeatures.tsx
  setting/setting-view/src/components/SettingUI/SettingInputs/SettingInputs.tsx
  setting/setting-view/src/components/SettingUI/SettingModalPage/NavSetting/NavSetting.tsx
  setting/setting-view/src/components/SettingUI/SettingModalPage/SettingModalWrap/SettingModalWrap.tsx
  setting/setting-view/src/css/custom.css
  setting/setting-view/src/modules/jsonState.ts
Labels: feature

#52 :recycle: fix: navbar 동적 로딩 안되는 것 해결
  bsmodules.js
  docs/doc0/doc0.md
  docusaurus.config.js
  setting/setting-view/bsmodules.js
  setting/setting-view/docs/doc0/doc0.md
  setting/setting-view/docs/doc1/doc1.md
  setting/setting-view/docusaurus.config.js
  setting/setting-view/sidebars.js
  setting/setting-view/src/lib/applycustomCss.ts
  setting/setting-view/src/lib/bsmodules.js
  setting/setting-view/src/theme/Root.tsx
  sidebars.js
  src/lib/applycustomCss.ts
  src/lib/bsmodules.js
  src/theme/Root.tsx
Labels: feature, fix

#60 :sparkles: update: /api/file/markdown [post] api response add filename
  setting/setting-server/controller.js
  setting/setting-server/middleware/markdown.middleware.js
  setting/setting-server/modules/fsmodules.js
Labels: enhancement

#61 :sparkles: update: button hover cursor pointer
  setting/setting-view/beauty.saurus.config.json
  setting/setting-view/src/components/HomepageFeatures.module.css
  setting/setting-view/src/components/SettingUI/SettingHoverBtn/SettingHover.module.css
Labels: enhancement

#62 :sparkles: update: hide darkTheme toggle button and add github href
  setting/setting-view/beauty.saurus.config.json
  setting/setting-view/src/lib/applycustomCss.ts
  setting/setting-view/src/theme/Navbar/index.tsx
Labels: enhancement

#67 :art: Feature/feature font color, navbar font color change
  setting/setting-view/beauty.saurus.config.json
  setting/setting-view/src/components/HomepageFeatures.module.css
  setting/setting-view/src/components/HomepageFeatures.tsx
  setting/setting-view/src/components/SettingUI/SettingModalPage/FeatureSetting/BasicFeatureSetting.tsx
  setting/setting-view/src/components/SettingUI/SettingModalPage/NavSetting/NavSetting.tsx
  setting/setting-view/src/css/custom.css
  setting/setting-view/src/data/InitialJson.ts
  setting/setting-view/src/lib/applycustomCss.ts
  setting/setting-view/src/theme/Navbar/index.tsx
  setting/setting-view/src/types/wholeJson.d.ts
Labels: feature

#69 Feature/markdown drapdrop
  setting/setting-server/controller.js
  setting/setting-server/index.js
  setting/setting-server/middleware/markdown.middleware.js
  setting/setting-server/modules/fsmodules.js
  setting/setting-view/src/asset/DeleteIconColor.tsx
  setting/setting-view/src/asset/UploadIconColor.tsx
  setting/setting-view/src/components/drag/DragDrop.module.css
  setting/setting-view/src/components/drag/DragDrop.tsx
  setting/setting-view/src/lib/applycustomCss.ts
  setting/setting-view/src/theme/DocSidebar/index.js
  setting/setting-view/src/theme/DocSidebarItem/index.js
  setting/setting-view/src/theme/DocSidebarItem/styles.module.css
Labels: feature

#70 :art: package.json script 추가
  package.json
Labels: feature

#72 :bug: fix:fontcolor link, item link to, basic bg
  setting/setting-view/beauty.saurus.config.json
  src/components/HomepageFeatures.tsx
  src/css/custom.css
  src/lib/applycustomCss.ts
  src/theme/Navbar/index.js
  src/theme/Navbar/styles.module.css
Labels: fix
